### ISSUE TITLE
How to train model Detectron2 on custom dataset

### ISSUE THREAD

**Issue by FirasAbdennadher** [oguchi-ebube/oguchiebube7-gmail.com#1]
Hello , nice work.
i have my own dataset trained with Detectron2, i want to know how to can I properly run Detectron2 on Videos ? any tuto or smth ?

**Comment by oguchi-ebube** [comment]
Thanks @FirasAbdennadher .
There isn't a specific tutorial on this process, I basically had to make series of research to get a hang of it.
I will recommend going through what this guy did(https://www.linkedin.com/pulse/journey-towards-creating-basketball-mini-map-stephan-janssen/), I think you can learn a few things.
